class WorkoutExercise {
  final String id;
  final String name;
  final String category;
  final String equipment;
  final String gifPath;
  final String description;
  final double caloriesPerMinute;

  WorkoutExercise({
    required this.id,
    required this.name,
    required this.category,
    required this.equipment,
    required this.gifPath,
    required this.description,
    required this.caloriesPerMinute,
  });
}

final List<WorkoutExercise> masterExerciseList = [
  // Chest
  WorkoutExercise(
    id: 'ch_01',
    name: 'Classic Pushups',
    category: 'Chest',
    equipment: 'None',
    gifPath: 'assets/gifs/ch_01.gif',
    description: 'A classic upper body exercise that targets the chest, shoulders, and triceps.',
    caloriesPerMinute: 7.0,
  ),
  WorkoutExercise(
    id: 'ch_02',
    name: 'Wide Arm Pushups',
    category: 'Chest',
    equipment: 'None',
    gifPath: 'assets/gifs/ch_02.gif',
    description: 'A variation of pushups that emphasizes the outer chest muscles.',
    caloriesPerMinute: 7.5,
  ),
  WorkoutExercise(
    id: 'ch_03',
    name: 'Incline Pushups',
    category: 'Chest',
    equipment: 'Chair/Bench',
    gifPath: 'assets/gifs/ch_03.gif',
    description: 'Performed with hands on an elevated surface to target the lower chest.',
    caloriesPerMinute: 6.0,
  ),
  WorkoutExercise(
    id: 'ch_04',
    name: 'Dumbbell Press',
    category: 'Chest',
    equipment: 'Dumbbells',
    gifPath: 'assets/gifs/ch_04.gif',
    description: 'Lying on your back, press dumbbells upwards to build chest strength.',
    caloriesPerMinute: 8.0,
  ),
  WorkoutExercise(
    id: 'ch_05',
    name: 'Dumbbell Flyes',
    category: 'Chest',
    equipment: 'Dumbbells',
    gifPath: 'assets/gifs/ch_05.gif',
    description: 'Isolation exercise for the chest performed by opening arms wide.',
    caloriesPerMinute: 6.5,
  ),
  // Abs
  WorkoutExercise(
    id: 'ab_01',
    name: 'Crunches',
    category: 'Abs',
    equipment: 'None',
    gifPath: 'assets/gifs/ab_01.gif',
    description: 'Target the upper abdominal muscles with controlled torso curls.',
    caloriesPerMinute: 4.0,
  ),
  WorkoutExercise(
    id: 'ab_02',
    name: 'Leg Raises',
    category: 'Abs',
    equipment: 'None',
    gifPath: 'assets/gifs/ab_02.gif',
    description: 'Excellent for targeting the lower abs by lifting legs while lying down.',
    caloriesPerMinute: 5.0,
  ),
  WorkoutExercise(
    id: 'ab_03',
    name: 'Plank',
    category: 'Abs',
    equipment: 'None',
    gifPath: 'assets/gifs/ab_03.gif',
    description: 'A core stability exercise that engages multiple muscle groups.',
    caloriesPerMinute: 3.5,
  ),
  WorkoutExercise(
    id: 'ab_04',
    name: 'Russian Twists',
    category: 'Abs',
    equipment: 'None',
    gifPath: 'assets/gifs/ab_04.gif',
    description: 'Target your obliques by twisting your torso from side to side.',
    caloriesPerMinute: 6.0,
  ),
  WorkoutExercise(
    id: 'ab_05',
    name: 'Mountain Climbers',
    category: 'Abs',
    equipment: 'None',
    gifPath: 'assets/gifs/ab_05.gif',
    description: 'A high-intensity core exercise that also boosts cardio.',
    caloriesPerMinute: 8.0,
  ),
  // Legs
  WorkoutExercise(
    id: 'lg_01',
    name: 'Bodyweight Squat',
    category: 'Legs',
    equipment: 'None',
    gifPath: 'assets/gifs/lg_01.gif',
    description: 'Fundamental lower body move targeting quads and glutes.',
    caloriesPerMinute: 6.0,
  ),
  WorkoutExercise(
    id: 'lg_02',
    name: 'Forward Lunges',
    category: 'Legs',
    equipment: 'None',
    gifPath: 'assets/gifs/lg_02.gif',
    description: 'Unilateral leg exercise for balance and lower body strength.',
    caloriesPerMinute: 7.0,
  ),
  WorkoutExercise(
    id: 'lg_03',
    name: 'Glute Bridges',
    category: 'Legs',
    equipment: 'None',
    gifPath: 'assets/gifs/lg_03.gif',
    description: 'Isolates the glutes and hamstrings while lying on the floor.',
    caloriesPerMinute: 4.5,
  ),
  WorkoutExercise(
    id: 'lg_04',
    name: 'Calf Raises',
    category: 'Legs',
    equipment: 'None',
    gifPath: 'assets/gifs/lg_04.gif',
    description: 'Simple but effective move to target the gastrocnemius muscles.',
    caloriesPerMinute: 3.0,
  ),
  WorkoutExercise(
    id: 'lg_05',
    name: 'Dumbbell Squats',
    category: 'Legs',
    equipment: 'Dumbbells',
    gifPath: 'assets/gifs/lg_05.gif',
    description: 'Added resistance to squats for increased leg muscle growth.',
    caloriesPerMinute: 8.5,
  ),
  // Arms
  WorkoutExercise(
    id: 'ar_01',
    name: 'Bicep Curls',
    category: 'Arms',
    equipment: 'Dumbbells',
    gifPath: 'assets/gifs/ar_01.gif',
    description: 'Classic move to build the biceps using dumbbells.',
    caloriesPerMinute: 5.0,
  ),
  WorkoutExercise(
    id: 'ar_02',
    name: 'Tricep Dips',
    category: 'Arms',
    equipment: 'Chair/Bench',
    gifPath: 'assets/gifs/ar_02.gif',
    description: 'Use a bench or chair to dip and build strong triceps.',
    caloriesPerMinute: 6.0,
  ),
  WorkoutExercise(
    id: 'ar_03',
    name: 'Hammer Curls',
    category: 'Arms',
    equipment: 'Dumbbells',
    gifPath: 'assets/gifs/ar_03.gif',
    description: 'Targets the brachialis and brachioradialis for thicker arms.',
    caloriesPerMinute: 5.0,
  ),
  WorkoutExercise(
    id: 'ar_04',
    name: 'Diamond Pushups',
    category: 'Arms',
    equipment: 'None',
    gifPath: 'assets/gifs/ar_04.gif',
    description: 'A pushup variation that heavily targets the triceps.',
    caloriesPerMinute: 7.5,
  ),
  WorkoutExercise(
    id: 'ar_05',
    name: 'Overhead Extension',
    category: 'Arms',
    equipment: 'Dumbbells',
    gifPath: 'assets/gifs/ar_05.gif',
    description: 'Isolate the triceps by extending a weight overhead.',
    caloriesPerMinute: 5.5,
  ),
  // Back
  WorkoutExercise(
    id: 'bk_01',
    name: 'Superman',
    category: 'Back',
    equipment: 'None',
    gifPath: 'assets/gifs/bk_01.gif',
    description: 'Lying on your belly, lift arms and legs to strengthen lower back.',
    caloriesPerMinute: 4.0,
  ),
  WorkoutExercise(
    id: 'bk_02',
    name: 'Dumbbell Rows',
    category: 'Back',
    equipment: 'Dumbbells',
    gifPath: 'assets/gifs/bk_02.gif',
    description: 'Build upper back and lat strength with controlled rowing.',
    caloriesPerMinute: 7.5,
  ),
  WorkoutExercise(
    id: 'bk_03',
    name: 'Bird Dog',
    category: 'Back',
    equipment: 'None',
    gifPath: 'assets/gifs/bk_03.gif',
    description: 'Improves core stability and lower back health.',
    caloriesPerMinute: 3.5,
  ),
  WorkoutExercise(
    id: 'bk_04',
    name: 'Pull-ups',
    category: 'Back',
    equipment: 'Bar',
    gifPath: 'assets/gifs/bk_04.gif',
    description: 'Advanced compound move for back and arm development.',
    caloriesPerMinute: 9.0,
  ),
  WorkoutExercise(
    id: 'bk_05',
    name: 'Renegade Rows',
    category: 'Back',
    equipment: 'Dumbbells',
    gifPath: 'assets/gifs/bk_05.gif',
    description: 'Combines planking with rowing for back and core power.',
    caloriesPerMinute: 8.5,
  ),
];
